apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: practicum-tks
resources:
  - platform.yaml
  - portal.yaml
  - admin-portal.yaml
  - generated
configMapGenerator:
  - name: practicum-request-controller-code
    files:
      - app/controller.py
  - name: practicum-self-service-portal-code
    files:
      - app/portal.py
  - name: practicum-vm-admin-portal-code
    files:
      - app/admin_portal.py
generatorOptions:
  annotations:
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
