apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: practicum-tks
resources:
  - platform.yaml
  - generated
configMapGenerator:
  - name: practicum-request-controller-code
    files:
      - app/controller.py
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
