apiVersion: demo.practicum/v1
kind: EnvironmentRequest
metadata:
  name: practicum-env-marina-git-224804
spec:
  owner: marina-volkova-practicum
  email: marina.volkova.practicum@demo.local
  groups:
    - practicum-qa-devs
  profile: app-with-vm
  purpose: git-demo
  ttl: 2h
  createdAt: 2026-06-23T19:48:04Z
