apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachineOperation
metadata:
  name: practicum-env-alice-demo-08fbfe-stop-68f934
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/environment: practicum-env-alice-demo-08fbfe
    demo.practicum/action: practicum-env-alice-demo-08fbfe-stop-vm-68f934
spec:
  type: Stop
  virtualMachineName: practicum-env-alice-demo-08fbfe-vm
