apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-service-portal
resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - dex-authenticator.yaml
configMapGenerator:
  - name: self-service-portal-app
    files:
      - server.py=app/server.py
generatorOptions:
  disableNameSuffixHash: true
