apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: practicum-tks
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.2/manifests/namespace-install.yaml
  - workload-rbac.yaml
  - practicum-demo-application.yaml
commonAnnotations:
  demo.deckhouse.io/description: "4 practicum"
images:
  - name: ghcr.io/dexidp/dex
    newName: docker.io/dexidp/dex
    newTag: v2.45.0
  - name: public.ecr.aws/docker/library/redis
    newName: docker.io/library/redis
    newTag: 8.2.3-alpine
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 1Gi
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-dex-server
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - op: add
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - op: add
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
      - op: add
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        accounts.practicum-admin: apiKey, login
        accounts.practicum-admin.enabled: "true"
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
      data:
        policy.default: role:readonly
        policy.csv: |
          p, role:practicum-admin, applications, *, */*, allow
          p, role:practicum-admin, applicationsets, *, */*, allow
          p, role:practicum-admin, repositories, *, *, allow
          p, role:practicum-admin, clusters, get, *, allow
          p, role:practicum-admin, projects, get, *, allow
          p, role:practicum-admin, logs, get, */*, allow
          p, role:practicum-admin, exec, create, */*, allow
          g, practicum-admin, role:practicum-admin
