apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: practicum-argocd-workload-manager
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/log"]
    verbs: ["get", "create"]
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-practicum-manager-token
  namespace: practicum-tks
  annotations:
    kubernetes.io/service-account.name: argocd-application-controller
    demo.deckhouse.io/description: "4 practicum"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: practicum-argocd-workload-manager
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: practicum-tks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: practicum-argocd-workload-manager
