apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualDisk
metadata:
  name: practicum-golden-builder-root
  namespace: practicum-tks
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/scenario: golden-image
    demo.practicum/image-role: builder
spec:
  dataSource:
    type: ObjectRef
    objectRef:
      kind: VirtualImage
      name: practicum-alpine-base-3-23-v1
  persistentVolumeClaim:
    size: 512Mi
    storageClassName: replicated
---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: practicum-golden-builder-vm
  namespace: practicum-tks
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/scenario: golden-image
    demo.practicum/image-role: builder
spec:
  virtualMachineClassName: generic
  runPolicy: AlwaysOnUnlessStoppedManually
  osType: Generic
  bootloader: BIOS
  cpu:
    cores: 1
    coreFraction: 5%
  memory:
    size: 512Mi
  blockDeviceRefs:
    - kind: VirtualDisk
      name: practicum-golden-builder-root
  provisioning:
    type: UserData
    userData: |
      #cloud-config
      hostname: practicum-golden-builder-vm
      users:
        - name: ansible
          lock_passwd: true
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/sh
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICulLQqgJayA+H56J/U03/3ncAeBlA2uedy6s235e/Wd 4 practicum AWX
      ssh_pwauth: false
      package_update: false
      packages:
        - openssh
        - python3
        - sudo
      runcmd:
        - install -d -m 0700 -o ansible -g ansible /home/ansible/.ssh
        - echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICulLQqgJayA+H56J/U03/3ncAeBlA2uedy6s235e/Wd 4 practicum AWX' > /home/ansible/.ssh/authorized_keys
        - chown ansible:ansible /home/ansible/.ssh/authorized_keys
        - chmod 0600 /home/ansible/.ssh/authorized_keys
        - rc-update add sshd default || true
        - service sshd start || true
