# Minimal real DVP example for clusters with Deckhouse Virtualization Platform.
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: postgres-vm
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  virtualMachineClassName: generic
  runPolicy: AlwaysOnUnlessStoppedManually
  osType: Generic
  bootloader: BIOS
  cpu:
    cores: 1
    coreFraction: 5%
  memory:
    size: 512Mi
  blockDeviceRefs:
    - kind: VirtualDisk
      name: postgres-vm-root
  provisioning:
    type: UserData
    userData: |
      #cloud-config
      hostname: postgres-vm
      users:
        - name: ansible
          lock_passwd: false
          passwd: $1$demoans$ZvqsQCamGDBaHD6nqXyqT/
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/sh
      ssh_pwauth: true
