apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: dev-alice-koroleva-feature-f72b
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-read
  namespace: dev-alice-koroleva-feature-f72b
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: ["", "apps", "networking.k8s.io", "virtualization.deckhouse.io"]
    resources: ["pods", "services", "deployments", "ingresses", "virtualmachines", "virtualdisks"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-read
  namespace: dev-alice-koroleva-feature-f72b
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: dev-alice-koroleva-feature-f72b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-read
