apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-demo-projects-claim
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi

