apiVersion: apps/v1
kind: Deployment
metadata:
  name: practicum-env-marina-feature-6639ff
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
    demo.practicum/expires-at: "2026-06-10T15:22:47Z"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/environment: practicum-env-marina-feature-6639ff
    demo.practicum/owner: marina-volkova-practicum
    demo.practicum/expires-at: 20260610T152247Z
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practicum-env-marina-feature-6639ff
  template:
    metadata:
      labels:
        app: practicum-env-marina-feature-6639ff
        demo.practicum/environment: practicum-env-marina-feature-6639ff
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: practicum-env-marina-feature-6639ff
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
    demo.practicum/expires-at: "2026-06-10T15:22:47Z"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/environment: practicum-env-marina-feature-6639ff
    demo.practicum/owner: marina-volkova-practicum
    demo.practicum/expires-at: 20260610T152247Z
spec:
  selector:
    app: practicum-env-marina-feature-6639ff
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practicum-env-marina-feature-6639ff
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
    demo.practicum/expires-at: "2026-06-10T15:22:47Z"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/environment: practicum-env-marina-feature-6639ff
    demo.practicum/owner: marina-volkova-practicum
    demo.practicum/expires-at: 20260610T152247Z
spec:
  ingressClassName: nginx
  rules:
    - host: practicum-env-marina-feature-6639ff.d8case.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: practicum-env-marina-feature-6639ff
                port:
                  name: http
