apiVersion: v1
kind: Namespace
metadata:
  name: dev-alice-001
  labels:
    demo.platform/self-service: "true"
    demo.platform/owner: alice
    demo.platform/team: payments
  annotations:
    demo.platform/profile: app-with-vm
    demo.platform/ttl: 8h
    demo.platform/request: dev-alice-001
    argocd.argoproj.io/sync-wave: "0"
