apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualDisk
metadata:
  name: dev-alice-001-vm-root
  namespace: dev-alice-001
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dataSource:
    type: ObjectRef
    objectRef:
      kind: ClusterVirtualImage
      name: alpine-base-3-23-v1
  persistentVolumeClaim:
    size: 256Mi
    storageClassName: k8nfs
---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: dev-alice-001-vm
  namespace: dev-alice-001
  labels:
    demo.platform/request: dev-alice-001
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  virtualMachineClassName: generic
  runPolicy: Manual
  osType: Generic
  bootloader: BIOS
  cpu:
    cores: 1
    coreFraction: 5%
  memory:
    size: 512Mi
  blockDeviceRefs:
    - kind: VirtualDisk
      name: dev-alice-001-vm-root
  provisioning:
    type: UserData
    userData: |
      #cloud-config
      hostname: dev-alice-001-vm
      users:
        - name: ansible
          lock_passwd: false
          passwd: $1$demoans$ZvqsQCamGDBaHD6nqXyqT/
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/sh
      ssh_pwauth: true
      package_update: false
      packages:
        - openssh
        - python3
        - sudo
      runcmd:
        - rc-update add sshd default || true
        - service sshd start || true
