apiVersion: v1
kind: LimitRange
metadata:
  name: customer-a-defaults
  namespace: customer-a
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
