apiVersion: v1
kind: LimitRange
metadata:
  name: practicum-default-container-resources
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      default:
        cpu: 500m
        memory: 512Mi
