apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/codex/demo.git
    targetRevision: main
    path: gitops/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
      - CreateNamespace=true
