apiVersion: v1
kind: Namespace
metadata:
  name: dev-alice-koroleva-feature-993e
  labels:
    self-service.demo/request: dev-alice-koroleva-feature-993e
    self-service.demo/owner: alice-koroleva
    self-service.demo/profile: app-only
    self-service.demo/purpose: feature
  annotations:
    self-service.demo/ttl: 2h
    argocd.argoproj.io/sync-wave: "0"
