apiVersion: demo.platform/v1
kind: EnvironmentRequest
metadata:
  name: dev-alice-koroleva-feature-54e6
spec:
  owner: alice-koroleva
  email: alice.koroleva@demo.local
  groups:
    - payments-devs
  profile: app-with-vm
  purpose: feature
  ttl: 2h
  access:
    exposeIngress: true
    sshToVm: false
  software:
    appImage: nginx:1.27
  vm:
    image: alpine-base-3-23-v1
    imageKind: ClusterVirtualImage
