apiVersion: demo.platform/v1
kind: EnvironmentRequest
metadata:
  name: dev-alice-001
spec:
  owner: alice
  team: payments
  profile: app-with-vm
  ttl: 8h
  access:
    exposeIngress: true
    sshToVm: false
  software:
    appImage: nginx:1.27
  vm:
    image: alpine-base-3-23-v1
