apiVersion: demo.platform/v1
kind: EnvironmentRequest
metadata:
  name: dev-alice-koroleva-demo-7266
spec:
  owner: alice-koroleva
  email: alice.koroleva@demo.local
  groups:
    - payments-devs
  profile: app-only
  purpose: demo
  ttl: 2h
  access:
    exposeIngress: true
    sshToVm: false
  software:
    appImage: nginx:1.27
