apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualDisk
metadata:
  name: dev-alice-koroleva-feature-54e6-vm-root
  namespace: dev-alice-koroleva-feature-54e6
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  dataSource:
    type: ObjectRef
    objectRef:
      kind: ClusterVirtualImage
      name: alpine-base-3-23-v1
  persistentVolumeClaim:
    size: 256Mi
    storageClassName: k8nfs
---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachine
metadata:
  name: dev-alice-koroleva-feature-54e6-vm
  namespace: dev-alice-koroleva-feature-54e6
  labels:
    self-service.demo/request: dev-alice-koroleva-feature-54e6
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  virtualMachineClassName: generic
  runPolicy: AlwaysOn
  osType: Generic
  bootloader: BIOS
  cpu:
    cores: 1
    coreFraction: 5%
  memory:
    size: 512Mi
  blockDeviceRefs:
    - kind: VirtualDisk
      name: dev-alice-koroleva-feature-54e6-vm-root
  provisioning:
    type: UserData
    userData: |
      #cloud-config
      hostname: dev-alice-koroleva-feature-54e6-vm
      users:
        - name: ansible
          lock_passwd: false
          passwd: $1$demoans$ZvqsQCamGDBaHD6nqXyqT/
          sudo: ALL=(ALL) NOPASSWD:ALL
          shell: /bin/sh
      ssh_pwauth: true
      package_update: false
      packages:
        - openssh
        - python3
        - sudo
        - qemu-guest-agent
      runcmd:
        - rc-update add sshd default || true
        - service sshd start || true
        - rc-update add qemu-guest-agent default || true
        - service qemu-guest-agent start || true
