apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - dvp-postgres-vm.yaml
  - golden-images
  - demo-app.yaml
  - monitoring.yaml
  - tenants/customer-a
  - ../../self-service/generated
