apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-app
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-app-read
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-app-read
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: demo-app
    namespace: demo-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-app-read
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-prod-quota
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: demo-prod-defaults
  namespace: demo-prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
