environmentSize: medium

app:
  name: demo-app
  replicas: 2
  image: nginx:1.27
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

vm:
  name: postgres-vm
  cpu: 1
  coreFraction: 10%
  memory: 512Mi
  diskSize: 256Mi

postgresql:
  shared_buffers: 1GB
  work_mem: 16MB

monitoring:
  enabled: true

goldenImage:
  source:
    type: HTTP
    url: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/generic_alpine-3.23.3-x86_64-bios-cloudinit-r0.qcow2
  importedImage:
    kind: VirtualImage
    name: alpine-base-3-23-v1
    namespace: demo-prod
  builderVm:
    name: golden-builder-vm
    cpu: 1
    coreFraction: 5%
    memory: 512Mi
    diskSize: 256Mi
    runPolicy: Manual
  outputImage:
    kind: VirtualImage
    name: alpine-golden-3-23-v1
    namespace: demo-prod
