apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: practicum-tks
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.19.1
commonAnnotations:
  demo.deckhouse.io/description: "4 practicum"
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.19.1
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.io/brancz/kube-rbac-proxy
    newTag: v0.15.0
patches:
  - target:
      version: v1
      kind: Namespace
      name: awx
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: awx
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: awx-operator-controller-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/imagePullSecrets
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: add
        path: /spec/template/spec/containers/1/imagePullPolicy
        value: IfNotPresent
