apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualMachineOperation
metadata:
  name: practicum-env-marina-bugfix-39884b-restart-5810f8
  namespace: practicum-tks
  annotations:
    demo.deckhouse.io/description: "4 practicum"
  labels:
    app.kubernetes.io/part-of: practicum-demo
    demo.practicum/environment: practicum-env-marina-bugfix-39884b
    demo.practicum/action: practicum-env-marina-bugfix-39884b-restart-vm-5810f8
spec:
  type: Restart
  virtualMachineName: practicum-env-marina-bugfix-39884b-vm
