apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - practicum-env-alice-bugfix-d634cb
  - practicum-env-alice-feature-175041
  - practicum-env-alice-feature-73cce8
  - practicum-env-alice-loadtest-893845
