apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-alice-koroleva-demo-7266-quota
  namespace: dev-alice-koroleva-demo-7266
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    pods: "8"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-alice-koroleva-demo-7266-defaults
  namespace: dev-alice-koroleva-demo-7266
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 256Mi
