apiVersion: v1
kind: Namespace
metadata:
  name: dev-alice-koroleva-demo-c3aa
  labels:
    self-service.demo/request: dev-alice-koroleva-demo-c3aa
    self-service.demo/owner: alice-koroleva
    self-service.demo/profile: app-with-vm
    self-service.demo/purpose: demo
  annotations:
    self-service.demo/ttl: 8h
    argocd.argoproj.io/sync-wave: "0"
